### PR TITLE
Changed the css and js links

### PR DESCRIPTION
**Pull request by m-oniqu3**
The bootstrap links were no longer working so I removed them and added a new one. The css files were also not being linked to the correct files so I fixed that as well.

### CODE REVIEW

**Review by tosibinaronmuro — APPROVED** [review]
Niceeee
This works 
Also could you change the “mmm” class lol

**Comment by tosibinaronmuro** [comment]
> The bootstrap links were no longer working so I removed them and added a new one. The css files were also not being linked to the correct files so I fixed that as well.

Yaaaay… this works lol

**Comment by m-oniqu3** [comment]
Okay. No problem.

**Comment by tosibinaronmuro** [comment]
> Okay. No problem.


I feel like a developer now😂

**Pull request merged**
